### ISSUE TITLE
no explanation in readme that explains pros/cons with web notification API

### ISSUE THREAD

**Issue by GrosSacASac** [lansana/chatty#1]
see title

**Comment by lansana** [comment]
Hi @GrosSacASac,

Thanks for your input! I think the main two differences are as follows:
1. Where the Web Notification API allows desktop notifications, this library does not.
2. Where this library allows customizing of the look and feel of your notification, the Web Notification API does not.

**Comment by GrosSacASac** [comment]
Another benefit is that Notification API, has more limited support, and may require permissions. Consider putting this information in the readme
